_wandb:
    value:
        cli_version: 0.26.0
        e:
            juszynvfzwuxz61l2obeic0a4irzavx5:
                codePath: src\tuning.py
                codePathLocal: tuning.py
                cpu_count: 2
                cpu_count_logical: 4
                disk:
                    /:
                        total: "314571747328"
                        used: "141979455488"
                email: 2351050127nhu@ou.edu.vn
                executable: D:\-Student-Performance-Prediction-Classification-\.venv\Scripts\python.exe
                git:
                    commit: 358fec78e6146a70705c4ac6d0fad7bc6b771e52
                    remote: https://github.com/vonhu2875/-Student-Performance-Prediction-Classification-.git
                host: BichNhu
                memory:
                    total: "8263585792"
                os: Windows-10-10.0.26200-SP0
                program: D:\-Student-Performance-Prediction-Classification-\src\tuning.py
                python: CPython 3.11.9
                root: D:\-Student-Performance-Prediction-Classification-\src
                startedAt: "2026-04-21T06:52:06.119542Z"
                writerId: juszynvfzwuxz61l2obeic0a4irzavx5
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 13
            "4": 3.11.9
            "5": 0.26.0
            "8":
                - 3
            "12": 0.26.0
            "13": windows-amd64
